import styles from "@/app/page.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Felicia Norman ♡ Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        {children}
      </body>
    </html>
  );
}
